### ISSUE TITLE
return local variables

### ISSUE THREAD

**Issue by uplusplus** [jmaye/libposlv#1]
const char\* SystemException::what() const throw() {
  std::stringstream stream;
  stream << mMsg << ": " << strerror(mErrno);
  if (mFilename != " ")
    stream << " [file = " << mFilename << "]" << "[line = " << mLine << "]";
  return stream.str().c_str();
}

stream is a local variable.

See also:
http://blog.sensecodons.com/2013/04/dont-let-stdstringstreamstrcstr-happen.html

**Comment by jmaye** [comment]
Thanks a lot for the input! I actually modified this code snippet in another project of mine, the idea was to store the output message string as a member of the class and then calling c_str on it. I will modify it here as well.
What I find strange though, that code was compiling without any warnings on at least 2 Ubuntu distributions (lucid and precise), I even have it built on PPA. The code is also running flawlessly on our platform. Probably, it never enters this portion of code, otherwise would segfault.

**Comment by uplusplus** [comment]
Thanks for your reply.
I am sorry for that I have not told you that I was trying to port the poslv core to Windows platform.
If I do not handle the 'SystemException',program would exit without any message when it happend.

Actually this code is running flawlessly on my ubuntu too,though  it is not in accord with the C plusplus standard.As you say,it is 'strange'.

I would like to know that where is the 'another project of mine' in your reply.And 
   Does it support the poslv 5.0?
   Does it support the Windows platform?

**Comment by jmaye** [comment]
I just corrected the bug in the exception classes. The other code I was referring too has nothing to do with libposlv, it's another project, but using more or less the same structures for exceptions. The current version of the exception classes is quite redundant, but it should do the trick. Ideally, one should factor out a superclass for it. Thanks anyway for pointing me to that.

About your other questions, what is poslv 5.0? The code will never be supported by Windows platform unfortunately as I'm working in a research environment and no one uses this system.

**Comment by uplusplus** [comment]
Applanix POS 5.0​
 PUBS-ICD-003759.pdfhttps://docs.google.com/file/d/0B0v79dhB86UJVEMydXIweUJmeVU/edit?usp=drive_web
​
I have ported the core to windows platform,expect the visualization module.
And I added external support for AP50.Now it works well with the new AP50
device on Windows.
Thanks for your great work.

2014-05-13 15:09 GMT+08:00 Jerome Maye notifications@github.com:

**Comment by jmaye** [comment]
Great! I was not aware that they released a new version of the document, but I guess this requires an update of the firmware of the POSLV computer. Do you think I should ask Applanix for it? Are there lots of changes?

**Comment by uplusplus** [comment]
There is something about the changes:

_1 Groups_

_3.2.4 Compatibility with Previous POS LV V4 Products_
The compatibility of POS LV V5 groups with POS LV V4 products is given as
follows:
 The POS LV V5 group format is the same as that of all POS LV V4 products.
 Groups 30, 31, 32, 33 have been added for additional events.

_3.3.1.24 Groups 30/31/32/33: Events 3/4/5/6_
The time and distance fields in this group indicate the time and distance
of Event ‘n’ discrete
signals that the POS receives. A client can use this message to attach
GPS/UTC time to external
events.

_2 Message_

_4.2.2 Compatibility with Previous POS LV V4 Products_
All POS LV V5 message formats are the same as POS LV V4 except as noted
below:
Message 33 has additional fields to control extra event inputs and the PPS
ouput.
Message 34 has additional valid values for the selection fields.

_//Message 33_
class EventDiscreteSetup :
  public Message {
public:
  ...
  /// Nominal number of bytes in the message
  static const uint16_t mByteCount = 8;
  /// Transaction number
  uint16_t mTransactionNumber;
  /// Event 1 trigger
  uint8_t mEvent1Trigger;
  /// Event 2 trigger
  uint8_t mEvent2Trigger;
_#ifdef AP50_
   /// Event 3 trigger
  uint8_t mEvent3Trigger;
  /// Event 4 trigger
  uint8_t mEvent4Trigger;
   /// Event 5 trigger
  uint8_t mEvent5Trigger;
  /// Event 6 trigger
  uint8_t mEvent6Trigger;

  //Event 1 Guard Time
  uint16_t mEvent1GuardTime;
  //Event 2 Guard Time
  uint16_t mEvent2GuardTime;
  //Event 3 Guard Time
  uint16_t mEvent3GuardTime;
  //Event 4 Guard Time
  uint16_t mEvent4GuardTime;
  //Event 5 Guard Time
  uint16_t mEvent5GuardTime;
  //Event 6 Guard Time
  uint16_t mEvent6GuardTime;

  //PPS Out polarity
  uint8_t mPPSOutPolarity;
  //PPS Out pulse width
  uint16_t mPPSOutPlusWith;

_#endif_
...
}

_//Message 34_
//values for the selection fields,for AP50
  /*
0 No input
1 Auxiliary 1 GNSS
2 Auxiliary 2 GNSS
3 Reserved
4 Base GNSS 1
5 Base GNSS 2
6 Reserved
7 GNSS 11
8 GNSS 21
9 ETHERNET
10-255 No input
*/

2014-05-13 16:56 GMT+08:00 Jerome Maye notifications@github.com:
