### ISSUE TITLE
Constructor 

### ISSUE THREAD

**Issue by uplusplus** [jmaye/libposlv#2]
TimeDistance::TimeDistance(const TimeDistance& other) :
    mTime1(other.mTime1),
    mTime2(other.mTime2),
    mDistanceTag(other.mDistanceTag),
    mTimeType(mTimeType),       //fix it
    mDistanceType(mDistanceType) {   //fix it
}

TimeDistance& TimeDistance::operator = (const TimeDistance& other) {
  if (this != &other) {
    mTime1 = other.mTime1;
    mTime2 = other.mTime2;
    mDistanceTag = other.mDistanceTag;
    mTimeType = mTimeType; //fix it
    mDistanceType = mDistanceType;   //fix it
  }
  return *this;
}

**Comment by jmaye** [comment]
Corrected, thanks! I was probably distracted when I wrote the code:)
